"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createUserWithEmailAndPassword, GoogleAuthProvider, sendEmailVerification, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, signOut } from "firebase/auth";
import { doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { auth, db, firebaseConfigured } from "../../lib/firebase";
import { useAuth } from "../../components/AuthProvider";

export default function AuthPage() {
  const router = useRouter(); const params = useSearchParams(); const { user } = useAuth();
  const [mode, setMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [googleBusy, setGoogleBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (user?.emailVerified) router.replace(params.get("next") || "/dashboard"); }, [user, router, params]);

  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); setMessage(""); try { if (!firebaseConfigured) throw new Error("Firebase todavía no está configurado en Vercel."); if (mode === "signup") { if (password.length < 8) throw new Error("La contraseña debe tener al menos 8 caracteres."); const credential = await createUserWithEmailAndPassword(auth, email.trim(), password); await setDoc(doc(db, "users", credential.user.uid), { email: credential.user.email, name: name.trim() || null, role: "user", createdAt: serverTimestamp(), emailVerified: false }); await sendEmailVerification(credential.user); setMessage("Cuenta creada. Revisa tu correo y confirma tu dirección antes de entrar."); await signOut(auth); } else { const credential = await signInWithEmailAndPassword(auth, email.trim(), password); if (!credential.user.emailVerified) { await sendEmailVerification(credential.user); await signOut(auth); throw new Error("Tu correo aún no está verificado. Te enviamos un nuevo enlace de verificación."); } router.replace(params.get("next") || "/dashboard"); } } catch (err) { setError(err instanceof Error ? err.message : "No se pudo completar la operación."); } finally { setBusy(false); } }

  async function signInWithGoogle() { setGoogleBusy(true); setError(""); setMessage(""); try { if (!firebaseConfigured) throw new Error("Firebase todavía no está configurado en Vercel."); const provider = new GoogleAuthProvider(); provider.setCustomParameters({ prompt: "select_account" }); const credential = await signInWithPopup(auth, provider); const userRef = doc(db, "users", credential.user.uid); const existing = await getDoc(userRef); const existingData = existing.exists() ? existing.data() : null; const profileName = credential.user.displayName?.trim() || existingData?.name || null; const profile = { email: credential.user.email, name: profileName, provider: "google", emailVerified: credential.user.emailVerified, lastLoginAt: serverTimestamp() }; if (existing.exists()) { await setDoc(userRef, profile, { merge: true }); } else { await setDoc(userRef, { ...profile, role: "user", createdAt: serverTimestamp() }); } router.replace(params.get("next") || "/dashboard"); } catch (err) { const code = err && typeof err === "object" && "code" in err ? String((err as { code?: string }).code) : ""; const friendly = code === "auth/popup-closed-by-user" ? "Se cerró la ventana de Google antes de completar el acceso." : code === "auth/popup-blocked" ? "El navegador bloqueó la ventana de Google. Permite ventanas emergentes para LifeBoost AI e inténtalo de nuevo." : code === "auth/account-exists-with-different-credential" ? "Ya existe una cuenta con este correo usando otro método de acceso. Entra con ese método primero." : code === "permission-denied" ? "Firebase rechazó el acceso a los datos del perfil. Verifica las reglas de Firestore." : err instanceof Error ? err.message : "No se pudo iniciar sesión con Google."; setError(friendly); } finally { setGoogleBusy(false); } }

  async function resetPassword() { if (!email.trim()) { setError("Escribe tu correo primero."); return; } setBusy(true); setError(""); setMessage(""); try { await sendPasswordResetEmail(auth, email.trim()); setMessage("Si la cuenta existe, recibirás instrucciones para restablecer la contraseña."); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo enviar el correo."); } finally { setBusy(false); } }

  const disabled = busy || googleBusy;
  return <main className="min-h-screen bg-slate-950 px-6 py-16 text-white"><div className="mx-auto max-w-md"><a href="/" className="text-sm text-blue-400">← LifeBoost AI</a><div className="mt-8 rounded-3xl border border-slate-800 bg-slate-900/80 p-7"><h1 className="text-3xl font-bold">{mode === "login" ? "Iniciar sesión" : "Crear cuenta"}</h1><p className="mt-2 text-slate-400">Tu cuenta sincroniza tus datos de forma privada.</p><button type="button" onClick={signInWithGoogle} disabled={disabled} className="mt-7 flex w-full items-center justify-center gap-3 rounded-xl border border-slate-700 bg-white px-5 py-3 font-semibold text-slate-900 disabled:opacity-50"><span className="text-lg font-bold">G</span>{googleBusy ? "Conectando con Google…" : "Continuar con Google"}</button><div className="my-5 flex items-center gap-3 text-xs text-slate-500"><span className="h-px flex-1 bg-slate-800" /><span>o continúa con correo</span><span className="h-px flex-1 bg-slate-800" /></div><form onSubmit={submit} className="space-y-4">{mode === "signup" && <label className="block text-sm text-slate-400">Nombre<input value={name} onChange={e => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white" autoComplete="name" /></label>}<label className="block text-sm text-slate-400">Correo electrónico<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white" autoComplete="email" /></label><label className="block text-sm text-slate-400">Contraseña<input required type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white" autoComplete={mode === "signup" ? "new-password" : "current-password"} /></label><button disabled={disabled} className="w-full rounded-xl bg-blue-600 px-5 py-3 font-semibold disabled:opacity-50">{busy ? "Procesando…" : mode === "login" ? "Entrar" : "Crear cuenta"}</button></form>{mode === "login" && <button onClick={resetPassword} disabled={disabled} className="mt-4 text-sm text-blue-400">¿Olvidaste tu contraseña?</button>}{message && <p className="mt-5 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-300">{message}</p>}{error && <p className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</p>}<button onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); setMessage(""); }} className="mt-6 text-sm text-slate-400">{mode === "login" ? "¿No tienes cuenta? Crear una" : "¿Ya tienes cuenta? Iniciar sesión"}</button></div></div></main>;
}
